name: Publish to GitHub Packages

on:
  push:
    branches:
      - main
    paths:
      - "package.json"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check for version changes
        id: check_version
        run: |
          VERSION_CHANGED=$(git diff HEAD^ HEAD -- package.json | grep -c '"version"')
          echo "VERSION_CHANGED=$VERSION_CHANGED" >> $GITHUB_ENV
          
      - name: Print GITHUB_ENV
        run: cat $GITHUB_ENV
        
      - name: Setup Node.js
        if: env.VERSION_CHANGED == '1'
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
          scope: "@starkdefi"

      - name: Install dependencies
        if: env.VERSION_CHANGED == '1'
        run: npm ci

      - name: Build and Publish
        if: env.VERSION_CHANGED == '1'
        run: |
          npm run build
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM }}
