name: Publish to GitHub Packages

on:
  push:
    branches:
      - main
    paths:
      - "package.json"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check for version changes
        id: check_version
        run: |
          git fetch --depth=1 origin main
          VERSION_CHANGED=$(git diff --name-only --diff-filter=M origin/main package.json | grep package.json | wc -l)
          echo "VERSION_CHANGED=$VERSION_CHANGED" >> $GITHUB_ENV

      - name: Setup Node.js
        if: env.VERSION_CHANGED == '1'
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
          scope: "@starkdefi"

      - name: Install dependencies
        if: env.VERSION_CHANGED == '1'
        run: npm ci

      - name: Build and Publish
        if: env.VERSION_CHANGED == '1'
        run: |
          npm run build
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM }}
